global using System.Collections.Immutable;
global using System.Collections.ObjectModel;
global using System.Windows.Input;
global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using ExampleFramework.DevTools.Models;
global using ExampleFramework.DevTools.Presentation;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using Microsoft.UI.Xaml.Controls;
global using ApplicationExecutionState = Windows.ApplicationModel.Activation.ApplicationExecutionState;
